# Generated by Django 5.0 on 2025-11-05 00:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre del remitente', max_length=255)),
                ('email', models.EmailField(help_text='Email del remitente', max_length=254)),
                ('message', models.TextField(help_text='Mensaje del contacto')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('queued', 'En Cola'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='notificatio_status_bddd71_idx'), models.Index(fields=['email'], name='notificatio_email_92ef99_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], default='email', max_length=20)),
                ('to', models.EmailField(help_text='Destinatario', max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('queued', 'En Cola'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='pending', max_length=20)),
                ('source_service', models.CharField(blank=True, help_text='Servicio que solicitó la notificación', max_length=100)),
                ('idempotency_key', models.CharField(blank=True, help_text='Clave de idempotencia para evitar duplicados', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Notificación',
                'verbose_name_plural': 'Logs de Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='notificatio_status_361e70_idx'), models.Index(fields=['to'], name='notificatio_to_94eac8_idx'), models.Index(fields=['idempotency_key'], name='notificatio_idempot_d54945_idx')],
            },
        ),
    ]
